# Generated by Django 6.0.2 on 2026-02-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_data', models.JSONField()),
                ('predicted_grade', models.FloatField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
